steps:
  # Install dependencies
  - name: 'python:3.11-slim'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt', '--user']

  # Run tests
  - name: 'python:3.11-slim'
    entrypoint: 'python'
    args: ['-m', 'pytest', 'test_st_app.py']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/python-app:$COMMIT_SHA', '.']

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/python-app:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'restaurants-fsa'
      - '--platform=managed'
      - '--image=gcr.io/$PROJECT_ID/python-app:$COMMIT_SHA'
      - '--labels=managed-by=gcp-cloud-build-deploy-cloud-run'
      - '--region=europe-west2'
      - '--quiet'

images:
  - 'gcr.io/$PROJECT_ID/python-app:$COMMIT_SHA'
