[firebase]
apiKey = "AIzaSyBoWu6XiWgO7TaksJeScLZsADd0QUMoy30"
authDomain = "restaurantsfsafirebaseproject.firebaseapp.com"
projectId = "restaurantsfsafirebaseproject"
storageBucket = "restaurantsfsafirebaseproject.firebasestorage.app"
messagingSenderId = "498393550856"
appId = "1:498393550856:web:1c74491ce512b499e041bd"
measurementId = "G-RGGBLR20RM"
