[firebase]
apiKey = "AIzaSyBmbGsx3gfKJ9aJ5SkVKYPdoxpWZlB83js"
authDomain = "restaurants-fsa.firebaseapp.com"
projectId = "restaurants-fsa"
storageBucket = "restaurants-fsa.firebasestorage.app"
messagingSenderId = "977350563654"
appId = "1:977350563654:web:3444098f0d961df4927747"
measurementId = "G-KRFDT642KY"
